### ISSUE TITLE
As a user I would like to be able to see general information about the web component store (imprint, contact details, owner, etc.).

### ISSUE THREAD

**Issue by raiffeisennet** [noi-techpark/odh-web-components-store#15]

**Comment by Piiit** [comment]
@sseppi 

@uhufa added the https://webcomponents.opendatahub.testingmachine.eu/getting-started/ draft. Could you please inform Stefano D. to improve that.

The README shows how to add new pages. Short and informative... well done :-)

https://github.com/noi-techpark/odh-web-components-store/tree/development/frontend#adding-pages
