### ISSUE TITLE
Opening the detail view gives a 404 for the web component

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#22]
It tries to download it from localhost. Maybe we failed to configure the deployment correctly?

![Selection_065](https://user-images.githubusercontent.com/6096063/63520562-33680f00-c4f5-11e9-991e-2101bbd8c8eb.png)

A reload of the same side gives 
```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: component/c115c741-e236-4fb9-9420-5a7dfffba933
    RequestId: ED45DCCFF5B56156
    HostId: GJdbbXdVXuHef8SDZpShMbEQhXaZK74g5aKqpaO6tZFWJVsWWcVqqGd10lVxiY6jIk5KsLhmrY4=


```

**UPDATE** 
The 404 still exists as HTTP response, but it errors out to "index.html" where javascript takes over and retrieves the right web component. The 404 however should be fixed in future releases, although not visible for users, due to logging inconsistencies and wrong server stats.

**Comment by uhufa** [comment]
@localhost: this will be fixed in the next PR. basically it is a leftover from the techdemo I showed

@404: probably a problem with deployment. I'll investigate.

**Comment by alexlanz** [comment]
I made a change to the server configuration. Currently the page is served using AWS S3. There we have two configuration options:

1. Index Document:
  The default file that should be used when only inserting the domain name (ex. example.com). Here we have index.html.

2. Error Document:
  This field indicates the file that should be served when an url is requested for which no files exists on S3. So for example if the user requests example.com/webcomponent/xyz and the file webcomponent/xyz does not exist as file, then the server returns the error document. Previously we we had here no document configured, but now it also points to index.html.

The problem that now occurs is, that when an URL/file does not exist on the server, the server returns the index.html file, but with an 404 response. For the user everything seems to be ok, but for monitoring/statistics/logs it's not the right answer.

Here we should try to find another solution. One possible way would be to serve the page as SSR.

What do you say what we should do @Piiit  and @raiffeisennet / @uhufa ?
