### ISSUE TITLE
As IDM PM I want to integrate on suedtirol.info the weather web components developed by Belka.

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/odh-web-components-store#32]
- [x] Antonietta informs Belka to open the repository on Github.
- [ ] Check if it's possible to integrate the widgets independently from the project progress of the store.

**Comment by Piiit** [comment]
@niettadesantis Can this issue be closed?

**Comment by niettadesantis** [comment]
Good question. At the moment it's an issue of my colleague that are in contact with Elements for suedtirol.info because the integration in Pimcore is still to do...
Let's keep it open in the backlog, so I'll update you how it's proceeding.
