### ISSUE TITLE
As a web component store user, I want to use all meteorology widgets by Belka within my third party website

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#46]
- [x] Found a bug inside the crawler, that prevents downloading components from GitHub, if the manifest file is not correct (not only that version, but also all subsequent versions, that have a correct manifest file)
- [x] The CDN, API and crawler pipelines have a race condition, because they use the same build folder. If we run them at the same time, we do not know on which server certain packages get deployed (BUG).

- [x] https://github.com/BelkaLab/webcomp-weather
- [x] https://github.com/BelkaLab/webcomp-weather-video
- [x] https://github.com/BelkaLab/webcomp-weather-mountain
- [x] https://github.com/BelkaLab/webcomp-weather-forecast
> An error occurs while building this webcomp, wrote an email to Antonietta about this

**Comment by Piiit** [comment]
@niettadesantis Done, please test

**Comment by niettadesantis** [comment]
Works fine! thanks
