### ISSUE TITLE
As a tester of web components I want to have a snippet to test responsive designs and website integrations

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#50]
- [x] api: Create an preview API call, that takes a web component UUID, version and attributes and shows a regular web page with the snippet integrated
- [x] api: Make that preview secure, do not allow different snippets, just the regular one including attribute parsing and script download from the API/CDN itself, not given via URI params
- [x] webapp: Add this functionality to the web component store web app
- [x] webapp: Parse also manually inserted snippets, after a preview update has been pressed

**FEEDBACK**
- [x] api: Add a responsive container around the web component for mobile testing

**Comment by Piiit** [comment]
@rcavaliere @ohnewein @bertolla @RudiThoeni Done, please test... try various inputs from the web component configurator and also please try manual snippets (you need to press update preview before you can open it in a separate window)

Go to https://webcomponents.opendatahub.testingmachine.eu, open a detail page and click the "External window" button below the preview.

I needed to add this to the API since we wanted to generate content server-side, otherwise we would need again iframes, and security issues would exist due to script injection. So a different domain can prevent reading of session data etc.

**Comment by Piiit** [comment]
@niettadesantis @rcavaliere 
Finally, the store has a preview for testing... now I will see what we can do with styles and fonts... 

The preview can be tested for responsiveness on a desktop within a browser in "responsive design" mode (ctrl+shift+m in firefox) or developer tools > responsive design in general. On mobile it is not working right now, because I would need to add a responsive container around the web component (as the first feedback of Roberto brought up). That will be done soon...

**Comment by ohnewein** [comment]
Feature seems to work fine. And is really valuable, because most of the web components we have so far, are not responsive at all :-( 

One example:

![Screenshot_20200319-193006](https://user-images.githubusercontent.com/414797/77101891-4a81c780-6a18-11ea-9bbf-0327206067ff.jpg)

**Comment by rcavaliere** [comment]
Tested more deeply. It is a fantastic feature, @Piiit! 
On the browser the responsiveness works perfectly.
On a mobile I see the responsiveness, but with a very low level of zoom, see attachment.
Another open issue is relating to the fonts, which we already discussed last Sprint.
Otherwise everything super and brilliant, very useful for third parties!

![IMG_2305](https://user-images.githubusercontent.com/9825179/77140122-dfb4a880-6a78-11ea-9c90-62c58d657a9e.PNG)

**Comment by Piiit** [comment]
@ohnewein @rcavaliere It is now on production. Please feel free to open new issues, if you feel that something is missing in terms of features or bug fixes. I thought, that we could maybe add a style textarea to update and test full window integration. That could be part of the other open issue we have regarding web components (https://github.com/noi-techpark/odh-web-components/issues/15).

**Comment by rcavaliere** [comment]
@Piiit ok! As said, I would also like to involve external 3rd parties like STA to get "real" feedback about the usability of the web components and the issues in integrating in existing web-sites

**Comment by Piiit** [comment]
@rcavaliere Perfect. Just let me know if you like a feedback button or something like a "email me" on the preview site.
