### ISSUE TITLE
External window preview has problems with some parameter strings

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#53]
Example: See webcomp-kg with default query

It seems to be a problem with `?` inside parameters, which eliminate all previous whitespaces.
`SELECT  ?h` becomes `SELECT%3Fh`... The space is missing here!

```
https://api.webcomponents.opendatahub.testingmachine.eu/preview/567cb2e2-3e5d-421a-bf85-b8ecc500aab9/v0.5.0?attribs=view=%22map%22;endpoint=%22https%3A%2F%2Fsparql.opendatahub.bz.it%2Fsparql%22;query=%22PREFIXschema%3A%3Chttp%3A%2F%2Fschema.org%2F%0APREFIXgeo%3A%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%0ASELECT%3Fh%3Fpos%3FposLabel%3FposColor%3FposIcon%0AWHERE%7B%0A%3Fhaschema%3ALodgingBusiness%3B%0Ageo%3AasWKT%3Fpos%3B%0Aschema%3Aname%3FposLabel%3B%0Aschema%3Aaddress%3Fa.%0AFILTER(lang(%3FposLabel)%3D%27de%27)%0A%23Colors%0AOPTIONAL%7B%0A%3Fhaschema%3ACampground.%0ABIND(%27chlorophyll%2C0.5%27AS%3FposColor)%23Green%0A%7D%0AOPTIONAL%7B%0A%3Fhaschema%3ABedAndBreakfast.%0ABIND(%27viridis%2C0.1%27AS%3FposColor)%23Purple%0A%7D%0AOPTIONAL%7B%0A%3Fhaschema%3AHotel.%0ABIND(%27jet%2C0.3%27AS%3FposColor)%23Lightblue%0A%7D%0AOPTIONAL%7B%0A%3Fhaschema%3AHostel.%0ABIND(%27jet%2C0.8%27AS%3FposColor)%23Red%0A%7D%0AOPTIONAL%7B%0A%23default%0ABIND(%27jet%2C0.8%27AS%3FposColor)%23Red%0A%7D%0A%7D%0ALIMIT500%22;
```

In addition also `%` do not work:
```
https://api.webcomponents.opendatahub.bz.it/preview/f1321372-6629-4912-a331-77d5d91dd646/v0.8.1?attribs=locale=%22it%22;height=%22300%25%25%22;width=%2280%25%22;%25
```
...gives...
```json
{
  "errorCode": 500,
  "message": "URLDecoder: Incomplete trailing escape (%) pattern",
  "stacktrace": ""
}
```

**Comment by Piiit** [comment]
@ohnewein @niettadesantis Please test...

Configurations with whitespaces did not work correctly in an external preview window.
For instance, it was not possible to see the knowledge graph component externally, or the routeplanner had values without spaces in between words. Look at "Terme di Merano" vs "TermediMerano"...

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/b199dbd5-508c-4de2-b06c-401ff6151ad0

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/567cb2e2-3e5d-421a-bf85-b8ecc500aab9

**Comment by ohnewein** [comment]
Both web components work on external window, now. Great work!

**Comment by niettadesantis** [comment]
Works fine, thank you.

**Comment by Piiit** [comment]
Null values still not work... see https://github.com/noi-techpark/odh-web-components-store/issues/62

**Comment by Piiit** [comment]
@niettadesantis Fixed, please test again...

**Comment by niettadesantis** [comment]
This issue seems to be resolved. I've found another bug and will create a new issue!
