### ISSUE TITLE
As a user I would like to quickly find a web component.

### ISSUE THREAD

**Issue by raiffeisennet** [noi-techpark/odh-web-components-store#6]
Add description to the search

**Comment by Piiit** [comment]
@uhufa "Search custom elements" is a bit confusing as placeholder text here. I would write "Search all web components".

**Comment by Piiit** [comment]
@uhufa After search and ENTER, I cannot copy the URL and open it in a new browser window. It tells me the following:
```
404 Not Found

    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: search/any/map
    RequestId: 20AD200119E72DF2
    HostId: EUEG3Y7Ghk+DCYF/b9/r7vg1TXo1FkkJoLZL01P8aMswrdzfdJAZmxKXhkEbg+m3HZ1jVUPXJEs=

```
