### ISSUE TITLE
wcs-manifest/configurator bool fields show "invalid" sometimes

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#62]
See
https://webcomponents.opendatahub.testingmachine.eu/webcomponent/b199dbd5-508c-4de2-b06c-401ff6151ad0

**Comment by Piiit** [comment]
@niettadesantis @ohnewein 
Go to the link above and test if the toggle `Disable car routing` works, and does not show invalid value as error message (in red). It should also trigger updates in the snippet and preview

**Comment by Piiit** [comment]
It is not working, sorry... I have to test it further.

**Comment by Piiit** [comment]
OK v0.5.2 should work finally

**Comment by ohnewein** [comment]
Tested on my Android phone and looks good!

**Comment by Piiit** [comment]
@ohnewein Thx

**Comment by niettadesantis** [comment]
Disable car routing works fine now. The only thing is, that the parameter is not passed to the external window. In the external window the car routing is always enabled, also when the flag in the store page is set to disabled.

**Comment by Piiit** [comment]
@niettadesantis Fixed, please test again

**Comment by niettadesantis** [comment]
This issue seems to be resolved. I found another bug - I'll create a new issue for it!
