### ISSUE TITLE
Improve the "Get in touch" text

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#63]
From a meeting with @niettadesantis:
```
If you would like to become a member of the Open Data Hub Community as a Data Provider,
  Data Consumer or as a Contributer, you can meet us at our events or get in touch with us through e-mail.
  Write us an e-mail to help@opendatahub.bz.it! 
  --> should we add also help for web component consumers
  --> also for bug reports and feature requests (first go to github, second write a mail)
  --> issue tracker sends it also to idm if necessary (webmaster@suedtirol.info --> IDM Digital, not Elements)
```

**Comment by Piiit** [comment]
@rabans @sseppi What do you think about adding also web component consumers to the get in touch text?

**Comment by mrabans** [comment]
@sseppi @Piiit Hi both, I absolutely support this proposal. So we get some feedbacks about webcomponents too. All collected in the RT.

**Comment by Piiit** [comment]
@mrabans @sseppi I updated the text, please check on https://webcomponents.opendatahub.testingmachine.eu/

**Comment by niettadesantis** [comment]
Looks good!

**Comment by Piiit** [comment]
@niettadesantis Thx

**Comment by mrabans** [comment]
Great, but the link on the mailaddress points to the page itself and is not a mailto:

**Comment by Piiit** [comment]
@mrabans Thanks for testing, this is fixed now
