### ISSUE TITLE
As web component maintainer, I need a configurator tester/previewer to see if manifest files are correct

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#69]

**Comment by Piiit** [comment]
Done, please test @ https://webcomponents.opendatahub.testingmachine.eu/validator

**Comment by ohnewein** [comment]
Seams to work. Only improvement which I see is to make default value of options restricted to an existing entry. But maybe not.

At the moment the following is possible:

```
    "options": [
      {
        "key": "domain",
        "type": "select",
        "label": "Domain",
        "options": {
          "values": [
            "mobility",
            "tourism"
          ],
          "default": "agriculture"
        }
      },
```

Even if "agriculture" is none of the options.

**Comment by bertolla** [comment]
My technical viewpoint is that i see no errors, but somehow google analytics is in debug mode. On production it should not be but i guess your handling that already.

**Comment by Piiit** [comment]
@ohnewein I fixed now several things and made the validator more intelligent... Please test again. I also moved it under "tools" now.

**Comment by Piiit** [comment]
@bertolla Dunno about g analytics, lets open a new issue if it occurs in production

**Comment by Piiit** [comment]
@sseppi Please test if you have time, just copy/paste a wcs-manifest.json file from a web component project into the validator... See tools/validator on https://webcomponents.opendatahub.testingmachine.eu
