### ISSUE TITLE
The external window preview of the web components has an escape problem with the character "%".

### ISSUE THREAD

**Issue by niettadesantis** [noi-techpark/odh-web-components-store#71]
To test it, go e.g. to that page:
https://webcomponents.opendatahub.bz.it/webcomponent/f1321372-6629-4912-a331-77d5d91dd646
In the configuration field "width" or "height" insert "100%" and click "External window".

![image](https://user-images.githubusercontent.com/46811227/86445615-fecb0380-bd12-11ea-9ff5-b4dc82e2d1c5.png)

**Comment by Piiit** [comment]
@niettadesantis Fixed in development. It will soon get live!

**Comment by Piiit** [comment]
Testable with https://api.webcomponents.opendatahub.testingmachine.eu/preview/f1321372-6629-4912-a331-77d5d91dd646/v0.8.4?attribs=locale=%22en%22;height=%22780px%22;width=%22100%25%22;

**Comment by niettadesantis** [comment]
Seems working fine! 🐱‍🏍
