### ISSUE TITLE
Infrastructure: We reach the Github API quota too soon to deploy and update all web components

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/odh-web-components-store#78]
Since we make several calls to the Github API, we get API permission denied too soon, and therefore newer web components get never updated. 

To solve this until we have the new store, we should create a simple script that deploys web components while testing, or when the quota closes the connection for the rest of the day. 

This script must read the manifest file and origins file from the github repos, and insert files into the CDN server and update the database.

**Comment by Piiit** [comment]
@bertolla 

I have created a pipeline to immediately publish any web component. Please test under https://jenkins.testingmachine.eu/job/it.bz.opendatahub.webcomponents-store/job/webcomp.test-deploy/

This is just for us, to have them immediately online after their build and not wait for the crawler, which are also often out of quota for a day on the Github API. It is for internal testing purposes... Before you run it, you need to run the build pipeline of the web component that you want to publish. Then insert the name and git tag of that published job.

**Comment by bertolla** [comment]
There is currently no new webcomponent to build, so I will wait for that

**Comment by Piiit** [comment]
@bertolla You could test it with https://github.com/noi-techpark/webcomp-maps-noi/pull/2 after I have created the pipelines
... I will ping you :-)

**Comment by bertolla** [comment]
I did so, it works, but you still need to do things manually, which results in you going back and forth between failing pipelines and fixing stuff. I mean maybe the tagging could be done here and also the adding of the repo to valid origins.

**Comment by Piiit** [comment]
@bertolla It did not work, the store API gives 500... there is no UUID in the DB for that web component. I will reopen and fix this issue now...

**Comment by bertolla** [comment]
The pipeline run through without errors. If the Webcomponent store crashes now because of other reasons I guess it should be discussed in other issues.

**Comment by Piiit** [comment]
the problem was that the pipeline did something wrong, but did not catch that error due to a missing error checking

**Comment by Piiit** [comment]
I think, now it works correctly. That is, it fails when the wcs-manifest.json file is not correct...

See https://jenkins.testingmachine.eu/job/it.bz.opendatahub.webcomponents-store/job/webcomp.test-deploy/29/console

Please test again... no hurry thou... ;-)

**Comment by Piiit** [comment]
> I did so, it works, but you still need to do things manually, which results in you going back and forth between failing pipelines and fixing stuff. I mean maybe the tagging could be done here and also the adding of the repo to valid origins.

Yes, I started to create a web component store CLI for that... so we can afterwards easily build pipelines. I will add this things to another user story

**Comment by bertolla** [comment]
Component us now up and running, so it seems to work
